Fix compilation error part 1
src/dialogs/gnome-cmd-options-dialog.cc:272:58: error: format not a string literal, format string not check
ed [-Werror=format-nonliteral]
 - Just ignore warnings by pragma

src/dialogs/gnome-cmd-search-dialog.cc:1023:24: error: this statement may fall through
 - For now, I just ignored this by pragma, but you must review this

src/tags/../dict.h:151:7: error: declaration of 'TUPLE' shadows a previous local [-Werror=shadow]
 - Don't know well, however I removed this warning by not using typedef.

src/tags/gnome-cmd-tags-doc.cc:207:16: error: enumeration value 'TAG_NONE' not handled in switch [-Werror=s
witch-enum]
  - Just ignore warnings by pragma

src/tags/gnome-cmd-tags-doc.cc:254:73: error: 'GError* gsf_opendoc_metadata_read(GsfInput*, GsfDocMetaData*
)' is deprecated: Use 'gsf_doc_meta_data_read_from_odf' instead [-Werror=deprecated-declarations]
  - Use modern function, add check in configure.ac

src/tags/gnome-cmd-tags-doc.cc:268:67: error: 'GError* gsf_msole_metadata_read(GsfInput*, GsfDocMetaData*)'
 is deprecated: Use 'gsf_doc_meta_data_read_from_msole' instead [-Werror=deprecated-declarations]
  - Same above

src/tags/gnome-cmd-tags-exiv2.cc:61:9: error: enumeration value 'TAG_AUDIO_ALBUMARTIST' not handled in switch [-Werror=switch-enum]
  - Same above

src/tags/gnome-cmd-tags-poppler.cc:39:9: error: no previous declaration for 'gchar* pgd_format_date(time_t)' [-Werror=missing-declarations]
  - Change function to "static" (global function needs previous declaration if it is not static)

src/tags/gnome-cmd-tags-poppler.cc:52:51: error: format not a string literal, format string not checked [-Werror=format-nonliteral]
  - Same above, just ignore this by pragma

src/tags/gnome-cmd-tags-poppler.cc:188:6: error: no previous declaration for 'void gcmd_tags_poppler_load_metadata(GnomeCmdFile*)' [-Werror=missing-declarations]
  - Change function to "static", but note that it seems this function is not used anymore.