fix warning: use g_thread_new instead of deprecated g_thread_create
searcher.cc: In function ‘void g_viewer_searcher_start_search(GViewerSearcher*, gboolean)’:
searcher.cc:605:32: error: ‘GThread* g_thread_create(GThreadFunc, gpointer, gboolean, GError**)’ is deprecated: Use 'g_thread_new' instead [-Werror=deprecated-declarations]
     src->priv->search_thread = g_thread_create (search_func, (gpointer) src, TRUE, NULL);
                                ^~~~~~~~~~~~~~~

WARNING: completely untested (other than compiler warning dissapearing).
This might also need a glib minimum version bump in configure check.