gnome-cmd-advrename-lexer.ll: fix for switch-default
src/gnome-cmd-advrename-lexer.ll:156:42: error: switch missing default case [-Werror=switch-default]
likewise

gnome-cmd-advrename-lexer.cc:1205:15: error: switch missing default case [-Werror=switch-default]
   else switch ( yy_get_next_buffer(  ) )
  - This is from the output of flex, so cannot be modified. So we have to ignore this.