src/main.cc: remove deprecated g_thread_init with higher GLib
src/main.cc:106:24: error: 'void g_thread_init(gpointer)' is deprecated [-Werror=deprecated-declarations]

https://developer.gnome.org/glib/stable/glib-Deprecated-Thread-APIs.html#g-thread-init

calling g_thread_init() is no longer needed since GLib 2.32.0.
e440def440148691aaf7b2a40841d331291f7c30 should be opposite.