fix warning: unused variable
gnome-cmd-tags.cc:72:13: error: 'no_support_for_libgsf_tags_string' defined but not used [-Werror=unused-variable]
 static char no_support_for_libgsf_tags_string[] = N_("<OLE2 and ODF tags not supported>");
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem introduced in:

commit d2b2782b76b6842f9684322e7fd45cf738bd9907
"Properly report unsuported Doc.* tags"