searcher.cc: fix for unused-but-set-variable
src/intviewer/searcher.cc:373:20: error: variable 'n' set but not used [-Werror=unused-but-set-variable]
src/intviewer/searcher.cc:491:20: error: variable 'n' set but not used [-Werror=unused-but-set-variable]