src/utils.cc: Fix -Wformat for 32 bit
After 4fdbe339c7ace2a6161afa8de9841d9cb5912aa1 ,
now on 32bit (e.g. i686, armv7hl) the following errors are raised:

src/utils.cc:380:81: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'GnomeVFSFileSize {aka long long unsigned int}' [-Werror=format=]
                     g_snprintf (buf0, sizeof(buf0), "%lu %s ", size, prefixes[0]);
src/utils.cc:386:72: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'GnomeVFSFileSize {aka long long unsigned int}' [-Werror=format=]
                 gint len = g_snprintf (buf0, sizeof(buf0), "%lu ", size);
src/utils.cc:409:58: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'GnomeVFSFileSize {aka long long unsigned int}' [-Werror=format=]
             g_snprintf (buf0, sizeof(buf0), "%'lu ", size);
src/utils.cc:413:57: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'GnomeVFSFileSize {aka long long unsigned int}' [-Werror=format=]
             g_snprintf (buf0, sizeof(buf0), "%lu ", size);

size has GnomeVFSFileSize, which is unsigned long on 64bit (so %lu is okay),
however on 32bit it is unsigned long long, so it should be %llu.

Thankfully, there is a defined macro 'GNOME_VFS_SIZE_FORMAT_STR', so use this.