ARM/MIPS/etc: Fix for -Wcast-align
e.g.
libgcmd/libgcmd-widget-factory.cc: In function 'GtkWidget* create_spin(GtkWidget*, const gchar*, gint, gint, gint)':
/usr/include/glib-2.0/gobject/gtype.h:2212:63: error: cast from 'GTypeInstance* {aka _GTypeInstance*}' to 'GtkAdjustment* {aka _GtkAdjustment*}' increases required alignment of target type [-Werror=cast-align]
     ((ct*) g_type_check_instance_cast ((GTypeInstance*) ip, gt))
                                                               ^
/usr/include/glib-2.0/gobject/gtype.h:482:66: note: in expansion of macro '_G_TYPE_CIC'
 #define G_TYPE_CHECK_INSTANCE_CAST(instance, g_type, c_type)    (_G_TYPE_CIC ((instance), (g_type), c_type))
                                                                  ^~~~~~~~~~~
/usr/include/gtk-2.0/gtk/gtkadjustment.h:41:47: note: in expansion of macro 'G_TYPE_CHECK_INSTANCE_CAST'
 #define GTK_ADJUSTMENT(obj)                  (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_ADJUSTMENT, GtkAdjustment))
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
libgcmd/libgcmd-widget-factory.cc:303:44: note: in expansion of macro 'GTK_ADJUSTMENT'
     GtkWidget *spin = gtk_spin_button_new (GTK_ADJUSTMENT (adj), 1, 0);

Here adj is once casted into GTypeInstance* on GLib internal, then again is casted
into GtkAdjustment* on GLib internal, which may require more strict alignment than
GTypeInstance* on arm or MIPS or so.

We cannot touch GLib internals. Let's ignore these warnings with GCC pragma.
Resolves https://github.com/gcmd/gnome-commander/issues/21 .